// <auto-generated />
using System;
using ANG_Assessment.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ANG_Assessment.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260313083808_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.14");

            modelBuilder.Entity("ANG_Assessment.DB.Models.AlertSubscribe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubscribeDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubscribeEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AlertSubscribes");
                });

            modelBuilder.Entity("ANG_Assessment.DB.Models.WeatherRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("HumidityHigh")
                        .HasColumnType("REAL");

                    b.Property<double>("HumidityLow")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("TemperatureHigh")
                        .HasColumnType("REAL");

                    b.Property<double>("TemperatureLow")
                        .HasColumnType("REAL");

                    b.Property<string>("WeatherDesc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WindDirection")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("WindSpeedHigh")
                        .HasColumnType("REAL");

                    b.Property<double>("WindSpeedLow")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("WeatherRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
